apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoeks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/piumsudhara/ArgoEKS.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: argoeks

  syncPolicy:
    syncOptions:
      - CreateNamespace

    automated:
      selfHeal: true
      prune: true
